version: 2

updates:
  - package-ecosystem: "dotnet:nuget"
    directory: "/"
  - package-ecosystem: "dotnet:nuget"
    directory: "/HueShift2/HueShift2"
    schedule:
      interval: "daily"
  - package-ecosystem: "dotnet:nuget"
    directory: "/HueShift2/HueShift2Tests"
    schedule:
      interval: "daily"
