image: docker:latest
services:
  - docker:dind
before_script:
  - docker login -u "mholubinka1" -p "d868cf0c-2ecd-4918-8557-cda22458de96" docker.io
  
docker-build-master:

  stage: build
  script:
    - docker build --pull -t "index.docker.io/mholubinka1/hueshift2" .
    - docker push "index.docker.io/mholubinka1/hueshift2"
  only:
    - master
  tags:
    - docker

docker-build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - docker
    
