image: docker:latest
services:
  - docker:dind
before_script:
  - docker login -u "DOCKER_HUB_USER" -p "DOCKER_HUB_PASSWORD" $DOCKER_HUB_REGISTRY

  
docker-build-master:

  stage: build
  script:
    - docker build --pull -t "$DOCKER_HUB_REGISTRY_IMAGE" .
    - docker push "$DOCKER_HUB_REGISTRY_IMAGE"
  only:
    - master
  tags:
    - docker

docker-build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - docker
    
