image: docker:latest
services:
  - docker:dind
before_script:
  - docker login -u "meholubinka" -p "c52f0ff0-846d-44b5-a55a-6af4df8a36b1" docker.io

docker-build-master:

  stage: build
  script:
    - docker build --pull -t "index.docker.io/meholubinka/hueshift2" .
    - docker push "index.docker.io/meholubinka/hueshift2"
  only:
    - master
  tags:
    - docker

docker-build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - docker
    
